# Root logger
log4j.rootLogger=TRACE, stdout, server

# CONSOLE appender not used by default
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Threshold=INFO
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} | %-5.5p | %-16.16t | %-32.32c{1} | %X{bundle.id} - %X{bundle.name} - %X{bundle.version} | %m%n

log4j.appender.server=org.apache.log4j.net.SocketAppender
log4j.appender.server.Port=4561
log4j.appender.server.RemoteHost=localhost
log4j.appender.server.ReconnectionDelay=10000
